# Generated by Django 5.2.8 on 2025-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clienta', models.CharField(max_length=100)),
                ('servicio', models.CharField(choices=[('Manicura', 'Manicura'), ('Pedicura', 'Pedicura'), ('Semi', 'Semipermanente')], max_length=100)),
                ('fecha', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('pendiente', models.BooleanField(default=True)),
            ],
        ),
    ]
