# Generated by Django 5.2.8 on 2025-11-19 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clienta', models.CharField(max_length=100)),
                ('servicio', models.CharField(choices=[('Manicura', 'Manicura'), ('Pedicura', 'Pedicura'), ('Semi', 'Semipermanente')], max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(12, 0), '12:00'), (datetime.time(14, 0), '14:00'), (datetime.time(16, 0), '16:00')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
