# Generated by Django 5.2.8 on 2025-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
