# Generated by Django 5.2.8 on 2026-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Gelish', 'Gelish'), ('Soft gel', 'Soft gel'), ('Rubber', 'Rubber'), ('Retiro', 'Retiro')], max_length=100),
        ),
    ]
