# Generated by Django 5.2.8 on 2025-11-19 18:17

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE "Citas_cita"
            ALTER COLUMN fecha TYPE DATE USING NULL,
            ALTER COLUMN hora TYPE TIME USING NULL;
            """,
            reverse_sql=""
        )
    ]