# Generated by Django 5.2.8 on 2025-11-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='pendiente',
            new_name='estado',
        ),
    ]
