# Generated by Django 5.2.8 on 2025-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0002_rename_pendiente_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
