# Generated by Django 5.2.8 on 2025-11-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0003_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
    ]
