# Generated by Django 5.2.8 on 2025-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0003_cita_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Manicura', 'Manicura'), ('Pedicura', 'Pedicura'), ('Semipermanente', 'Semipermanente')], max_length=100),
        ),
    ]
