# Generated by Django 5.2.8 on 2025-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0005_alter_cita_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.TimeField(),
        ),
    ]
