# Generated by Django 5.2.8 on 2025-11-13 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0006_alter_cita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(12, 0), '12:00'), (datetime.time(14, 0), '14:00'), (datetime.time(16, 0), '16:00')]),
        ),
    ]
