# Generated by Django 5.2.8 on 2025-12-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0006_alter_cita_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('horarios', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
    ]
